# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_session_tutor'),
        ('tutors', '0002_auto_20171031_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='time_per_slot',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='course_taught',
        ),
        migrations.AddField(
            model_name='tutor',
            name='course_taught',
            field=models.ManyToManyField(to='tutorial.Course'),
        ),
    ]
