# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_auto_20171105_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=8)),
                ('course_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='tutor',
            name='course_taught',
            field=models.ManyToManyField(to='tutors.Course'),
        ),
    ]
