# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_auto_20171105_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotAvailableSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='tags',
            field=models.ManyToManyField(to='tutors.Tag'),
        ),
    ]
