# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_notavailableslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='rate_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
