# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_auto_20171113_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='course_taught',
            new_name='courseTaught',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='hourly_rate',
            new_name='hourlyRate',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='private_tutor',
            new_name='privateTutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='time_per_slot',
            new_name='timePerSlot',
        ),
    ]
