# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_tutor_show_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='courseTaught',
            field=models.ManyToManyField(blank=True, to='tutors.Course'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tutors.Tag'),
        ),
    ]
