# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20171031_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='wallet',
        ),
    ]
