# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_session_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='status',
        ),
        migrations.AddField(
            model_name='session',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
    ]
