# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_auto_20171105_1914'),
        ('tutorial', '0003_auto_20171105_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='course_code',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
