# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20171105_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('time_review', models.DateTimeField()),
                ('rating', models.FloatField(default=0)),
                ('rate_time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Session'),
        ),
    ]
