# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_auto_20171119_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rate_time',
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_review',
            field=models.DateTimeField(blank=True),
        ),
    ]
