# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_auto_20171119_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time_review',
            field=models.DateTimeField(null=True),
        ),
    ]
