# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20171126_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
